title: "Historical Carnatic Concert Programmes"
baseurl: "/carnatic-programmes"
url: ""

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .DS_Store
