title: "Parampara"
description: "Historical South Indian Music Conference Programmes"
baseurl: "/carnatic-programmes"
url: ""

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .DS_Store
